### ISSUE TITLE
Unable to produce correct production build

### ISSUE THREAD

**Issue by pb-** [cjohansen/dumdom#11]
Hello there :wave:,

I had no issues using dumdom during development, but I am failing to produce a working production build. Opening the page including the resulting main.js I get

![2020-12-06-170114_495x352_scrot](https://user-images.githubusercontent.com/84886/101285338-d759f480-37e4-11eb-96a0-da15f6280b76.png)

For steps to reproduce, I've created the following minimal broken example:

deps.edn:
```edn
{:deps {org.clojure/clojure       {:mvn/version "1.10.1"}
        org.clojure/clojurescript {:mvn/version "1.10.773"}
        cjohansen/dumdom          {:mvn/version "2020.10.19"}}}
```

src/issue/core.cljs (from the readme):
```cljs
(ns issue.core
  (:require [dumdom.core :as dumdom :refer [defcomponent]]))

(defcomponent heading
  :on-render (fn [dom-node val old-val])
  [data]
  [:h2 {:style {:background "#000"}} (:text data)])

(defcomponent page [data]
  [:div
   [heading (:heading data)]
   [:p (:body data)]])

(dumdom/render
  [page {:heading {:text "Hello world"}
         :body "This is a web page"}]
  (js/document.getElementById "app"))
```

index.html:
```html
<!DOCTYPE html>
<html>
  <body>
    <div id="app">
    </div>
    <script src="main.js" type="text/javascript"></script>
  </body>
</html>
```

I am building this with
```shell
clj -m cljs.main --optimizations advanced -c issue.core
```

Any help would be greatly appreciated. Is there something I am missing perhaps?

**Comment by pb-** [comment]
I took some time to bisect through the releases and found that the breakage was introduced between 2020.07.04 (works) and 2020.10.19 (does not work). Haven't seen anything super obvious, but perhaps that helps to narrow it down.

**Comment by augustl** [comment]
Can confirm, 2020.10.19 is broken with this very same error for me, 2020.07.04 works just fine though!

![image](https://user-images.githubusercontent.com/375/114241337-46a94600-9989-11eb-95b8-9ea482d7773a.png)

**Comment by augustl** [comment]
I have the build set up with `:infer-externs true`, and since we both get different symbol names, it seems like there's some symbol here that shouldn't be mangled, but for some reason is?

**Comment by asaade** [comment]
For what is worth, I have the same problem here with [cjohansen/dumdom "2020.10.19"] and when compiling with (set! *warn-on-infer* true) I get this error:
**WARNING: Cannot infer target type in expression (. e preventDefault) at line 13 src/asaade/components.cljs**
The code in question is a simple:
:onClick (fn [e]
                       (.preventDefault e)
                       (put! actions-ch (:id content)))

**Comment by cjohansen** [comment]
Holy shit! So sorry for not responding here @pb- You've probably given up on this a long time ago, but I just wanted to say sorry for not catching this. It seems my notification options on Github is to get email about everything I'm watching, or nothing at all. So I didn't see any of the issues filed here 😢 This is now fixed in 2021.05.07

**Comment by pb-** [comment]
@cjohansen no worries - I simply used the older version without issues. Thanks for creating dumdom :pray:!

**Comment by augustl** [comment]
The benefit of being in a relatively stable ecosystem is that not upgrading is a totally viable option :) 

Just bumped to the latest version, everything works fine now 🥳
