### ISSUE TITLE
support for data-* attributes?

### ISSUE THREAD

**Issue by oakmac** [cjohansen/dumdom#12]
I am trying to create some HTML with custom [data attributes] fields that will be referenced by an external library. Is this supported by dumdom?

A possible example of what I was looking for (this does not work currently):

```clj
(defcomponent SomeComponent
  []
  [:div {:data-foo-bar "wizzle"} "hello"])

;; <div data-foo-bar="wizzle">hello</div>
```

I see something in the snabbdom docs about a [dataset-module], but I was not sure how this mapped to dumdom (or if it maps at all).

<hr />

Many thanks for the fun library! I love the emphasis on stability:

> dumdom aims to be finished, stable, and worthy of your trust. Breaking changes will never be intentionally introduced to the codebase.

[data attributes]:https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
[dataset-module]:https://github.com/snabbdom/snabbdom#the-dataset-module

**Comment by cjohansen** [comment]
Sorry for the late response, but dumdom `2021.06.11` properly renders `data-*` attributes 👍

**Comment by oakmac** [comment]
> Sorry for the late response

No worries 🤓 

> dumdom 2021.06.11 properly renders data-* attributes 👍

Great news! Thank you for the work / update 🎉 🙏
