### ISSUE TITLE
Question: Why the double vector in Event handler data?

### ISSUE THREAD

**Issue by holyjak** [cjohansen/dumdom#22]
https://github.com/cjohansen/dumdom#event-handler-data shows

```
:on-click [[:fruit/select :apple]]
```

However it does not explain why this and not simply `:on-click [:fruit/select :apple]`. Or is it so that you could do either but for some reason you wish the `data` passed to the handler to actually be `[[...]]`?

**Comment by cjohansen** [comment]
Sorry for the late response... For some reason I don't get notifications for new Github issues :(

Anyway: the double vector is so you can have several actions. Each action is a vector with an action name and some arguments. But this is really just how I do it, and the API we ended up with does not care what data you pass. I'll try to clarify this point in the readme. Some background in this post: https://www.kodemaker.no/blogg/2021-11-mer-mindre/

**Comment by cjohansen** [comment]
I've updated the Readme, hope it's clearer now. Thanks for the feedback!
