### ISSUE TITLE
Hyphenated attributes not rendered correctly

### ISSUE THREAD

**Issue by raystubbs** [cjohansen/dumdom#47]
Given these attributes in hiccup:
![image](https://github.com/cjohansen/dumdom/assets/7083791/3bcce4cb-78a2-4bf7-b55c-bcb6d2c47611)

The DOM I get is:
![image](https://github.com/cjohansen/dumdom/assets/7083791/6e493917-186a-4788-a194-f0d933f542c3)

Not sure if this issue belongs here or in the Snabbdom repo.

**Comment by cjohansen** [comment]
It belongs here! I hadn't seen this issue (my Github notifications get lost somehow), but I ran into it myself, and it was fixed in november!
