### ISSUE TITLE
`onInput` event listener not receiving an event

### ISSUE THREAD

**Issue by raystubbs** [cjohansen/dumdom#48]
Any `onInput` event handler attached to `input` elements seem to receive some internal state rather than an event:
![image](https://github.com/cjohansen/dumdom/assets/7083791/48919cfe-b6f7-4c02-a77f-1aae2b9f72d4)

**Comment by raystubbs** [comment]
Eh, nope, I'm wrong.

**Comment by cjohansen** [comment]
Glad it sorted itself out 😅
