### ISSUE TITLE
Add support for shadow-cljs?

### ISSUE THREAD

**Issue by reinseth** [cjohansen/dumdom#8]
Background:
https://github.com/reagent-project/reagent/pull/441

Shadow-cljs does not support transitive dependencies via :foreign-libs in deps.cljs, but can resolve (and install) dependencies via :npm-deps as demonstrated in the reagent PR.

I'm not sure if adding :npm-deps will have any implications when used in combination with :foreign-libs, but I'm hoping that you do, @cjohansen :)

As a workaround dumdom can be added separately in package.json when using shadow-cljs, so this is definitively not a deal breaker, but would be nice to have.

UPDATE:
It seems that the solution does not seem to be as simple as just adding the :npm-deps dictionary. There are deeper problems which prevents dumdom to load properly at runtime when used with shadow-cljs :( I will try to find out exactly what it is that fails (the error messages aren't very insightful), but in the mean time feel free to close this issue unless you planning to start using shadow-cljs yourself.

**Comment by reinseth** [comment]
This is more complicated than I had hoped, so I'm just closing this.

**Comment by cjohansen** [comment]
I don't think adding `:npm-deps` has any negative effects for the existing toolchain. Is it not enough?

**Comment by reinseth** [comment]
After a little bit of digging, it seems that the prep/wiring in `snabbdom/source.js` is the source of the problem. Just loading snabbdom from npm is not sufficient for the setup of `dumdom.core/patch`. I'm sure how Reagent does this, but I'll have a look.

**Comment by cjohansen** [comment]
Ah. It's been a while, but I seem to remember that I had to build Snabbdom somehow, so that's why it's a git submodule currently. It should probably be updated 😬

**Comment by reinseth** [comment]
Snabbdom is available as cljsjs it seems, and then I think the patch function can be wired up by requiring all the different snabbdom modules, something like this:

```clj
(require '["snabbdom"]) ; => loads js/snabbdom
(require '["snabbdom/modules/attributes"]) ; => loads js/snabbdom_attributes
```

The issue that I haven't figured out yet is how to make this work with shadow-cljs. When snabbdom is loaded by shadow-cljs then the require calls doesn't assign to global variables, instead they work like regular requires:

```clj
; with shadow
(require '[snabbdom :as snabbdom]) ; js/snabbdom is _not_ assigned
```

Not sure what the best way to go about this would be... :thinking:

**Comment by cjohansen** [comment]
Snabbdom is only called in two places, maybe this will work?

```
(defn init [opts]
  (if js/snabbdom
    (js/snabbdom.init opts)
    (snabbdom/init opts)))

(def patch
  "The snabbdom patch function used by render"
  (init (clj->js [(.-eventlisteners js/snabbdom)
                  (.-attributes js/snabbdom)
                  (.-props js/snabbdom)
                  (.-style js/snabbdom)])))
```

**Comment by reinseth** [comment]
Using snabbdom from cljsjs turned out to be much easier than I first had thought :)
I have a branch that works for both figwheel and shadow-cljs where I have replaced the snabbdom submodule with the cljsjs lib:
https://github.com/reinseth/dumdom/tree/support-shadow-cljs

I can make a PR if that's ok!

**Comment by cjohansen** [comment]
Please do 👏 😄

**Comment by reinseth** [comment]
Great! Do you generate the pom.xml with tools.deps, or just do you just edit it by hand?

**Comment by cjohansen** [comment]
I generated it once with `clojure -Spom`, and then just update it by hand.

**Comment by reinseth** [comment]
:+1: 
I've created PR #9 and updated the versions in pom.xml and in the readme.
